<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Brands_model extends CI_Model
{

    public $table = 'brands';
    public $id = 'name';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->distinct();
        $this->db->select('UCASE(merk) as name');
        $this->db->from('stock');
        $this->db->where('kdgol2', $id);
        $this->db->order_by('merk', 'ASC');
        return $this->db->get()->result();
    }

    // get data by name
    function get_by_name($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Brands_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-05 15:06:21 */
/* http://harviacode.com */
