<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Carrier_model extends CI_Model
{

    public $table = 'carrier';
    public $id = 'code';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get allact
    function get_all_active()
    {
        $this->db->select('code, name');
        $this->db->where('active = "Y"');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('code, name');
        $this->db->where('code', $id);
        $this->db->order_by('code', 'ASC');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        
        if ($q) {
            $this->db->like('code', $q);
            $this->db->or_like('name', $q);
        }
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    function get_limit_data($limit, $start = 0, $q = NULL) { //
        
        $qry = $this->db->select('code, name, active');
        
        if ($q) {
            $this->db->like('code', $q);
            $this->db->or_like('name', $q);
        }
        $this->db->order_by($this->id, $this->order);
	    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Brands_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-05 15:06:21 */
/* http://harviacode.com */