<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Shopping_cart_model extends CI_Model
{

    public $table = 'shopping_cart';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_mbrid($id)
    {
        $this->db->select('id, mbrid');
        $this->db->where('mbrid', $id);
        $this->db->where('aktif', 'Y');
        return $this->db->get($this->table)->row();
    }

    // get detail by id
    function get_detail_by_id($id)
    {
        $this->db->select('s.kdbar, s1.kdurl, s1.nama, s.qty, s.hjual, format(s.hjual,0,"id") as hjualf, s1.gambar, s1.pnj, s1.lbr, s1.tgi, s1.berat');
        $this->db->from('shopping_cart_detail s, stock s1');
        $this->db->where('s.kdbar = s1.kdbar');
        $this->db->where('s.id', $id);
        $this->db->order_by('s.urut', 'ASC');
        return $this->db->get()->result();
    }

    function get_total_item_by_id($id)
    {
        $this->db->where('id', $id);
        $this->db->from('shopping_cart_detail');
        return $this->db->count_all_results();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete data
    function delete_detail($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete('shopping_cart_detail');
    }

}

/* End of file Brands_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-05 15:06:21 */
/* http://harviacode.com */
